### ISSUE TITLE
Screenshots to Readme

### ISSUE THREAD

**Issue by GantMan** [yakupafsin/WordpressMobileApp#6]
Would be nice to see either an animated GIF or some screenshots of the functionality in the Readme.

**Comment by yakupafsin** [comment]
Hi @GantMan, thank you for advice. I am planning to add little bit more details before adding the screenshots. But I will add screenshots as soon as posible.

**Comment by GantMan** [comment]
looking forward to it!!!

**Comment by yakupafsin** [comment]
Hi @GantMan, there is one screenshot finally 🥳
